# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='fira')),
            ],
            options={
                'verbose_name': 'Fira',
                'verbose_name_plural': 'Firas',
            },
        ),
    ]
